name: check backend

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Check path of changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

    # run if 'backend' or 'frontend' files were changed
    # this will be used to allow preloading of signins and other operations so they can be reused if both contain changes
    - name: preload
      if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true'
      run:
        - name: Set up QEMU
            uses: docker/setup-qemu-action@v1

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Log in to the Container registry
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

    # run only if 'backend' files were changed
    - name: backend build
      if: steps.filter.outputs.backend == 'true'
      run:
        - name: Build and push container image
          working-directory: backend/
          run: |
            docker buildx build --push \
            --tag hub-backend:latest \
            --platform linux/arm/v7 .

    # run only if 'frontend' files were changed
    - name: frontend build
      if: steps.filter.outputs.frontend == 'true'
      run:
        - name: Build and push container image
          working-directory: frontend/
          run: |
            docker buildx build --push \
            --tag hub-frontend:latest \
            --platform linux/arm/v7 .